import { cx } from "./cx"
import {
    B_COLOR,
    B_COLOR_BEFORE,
    BOTTOM_LEFT_CORNER_FULL,
    BOTTOM_RIGHT_CORNER_FULL,
    E_COLOR,
    E_COLOR_BEFORE, FRAME_COLOR,
    N_COLOR,
    N_COLOR_BEFORE,
    O_COLOR,
    O_COLOR_BEFORE,
    TOP_LEFT_CORNER_FULL_SHIFTED,
    TOP_LEFT_CORNER_FULL_SHIFTED_SMALL,
    TOP_RIGHT_CORNER_FULL_SHIFTED,
    TOP_RIGHT_CORNER_FULL_SHIFTED_SMALL,
    Z_COLOR,
    Z_COLOR_BEFORE,
} from "./classes"

export const dots: Record<number, string> = {
    100: cx(B_COLOR, "rounded-t-2xl"),
    124: B_COLOR,
    148: B_COLOR,
    172: B_COLOR,
    196: B_COLOR,
    220: B_COLOR,
    244: B_COLOR,
    268: cx(B_COLOR, "rounded-bl-2xl"),
    269: B_COLOR,
    270: B_COLOR,
    271: B_COLOR,
    272: cx(N_COLOR, B_COLOR_BEFORE, "before:block before:absolute before:inset-0 before:rounded-br-2xl"),
    248: B_COLOR,
    224: B_COLOR,
    200: cx(N_COLOR, B_COLOR_BEFORE, "before:block before:absolute before:inset-0 before:rounded-tr-2xl"),
    199: B_COLOR,
    198: cx(O_COLOR, BOTTOM_RIGHT_CORNER_FULL, O_COLOR_BEFORE),
    197: B_COLOR,
    78: cx(O_COLOR, "rounded-tl-2xl"),
    102: O_COLOR,
    126: O_COLOR,
    150: O_COLOR,
    174: O_COLOR,
    222: cx(O_COLOR, "rounded-bl-2xl"),
    223: O_COLOR,
    225: cx(O_COLOR, TOP_RIGHT_CORNER_FULL_SHIFTED_SMALL, N_COLOR_BEFORE),
    226: cx(E_COLOR, TOP_RIGHT_CORNER_FULL_SHIFTED, N_COLOR_BEFORE),
    202: cx(E_COLOR, BOTTOM_LEFT_CORNER_FULL, N_COLOR_BEFORE),
    178: cx(O_COLOR, E_COLOR_BEFORE, "before:block before:absolute before:inset-0 before:rounded-tl-2xl"),
    154: O_COLOR,
    130: O_COLOR,
    106: O_COLOR,
    136: cx(TOP_LEFT_CORNER_FULL_SHIFTED_SMALL, Z_COLOR_BEFORE),
    // 205: cx(TOP_LEFT_CORNER_FULL_SHIFTED_SMALL, Z_COLOR_BEFORE),
    159: cx(TOP_LEFT_CORNER_FULL_SHIFTED_SMALL, Z_COLOR_BEFORE),
    82: cx(O_COLOR, "rounded-tr-2xl"),
    79: O_COLOR,
    80: O_COLOR,
    81: O_COLOR,
    128: cx(N_COLOR, "rounded-t-2xl"),
    152: N_COLOR,
    176: N_COLOR,
    296: cx(N_COLOR, "rounded-b-2xl"),
    177: cx(BOTTOM_LEFT_CORNER_FULL, N_COLOR_BEFORE),
    227: cx(BOTTOM_LEFT_CORNER_FULL, N_COLOR_BEFORE),
    251: cx(E_COLOR, TOP_RIGHT_CORNER_FULL_SHIFTED, N_COLOR_BEFORE),
    132: cx(N_COLOR, "rounded-t-2xl"),
    156: N_COLOR,
    180: N_COLOR,
    204: N_COLOR,
    228: N_COLOR,
    252: N_COLOR,
    276: N_COLOR,
    300: cx(N_COLOR, "rounded-b-2xl"),
    201: cx(TOP_RIGHT_CORNER_FULL_SHIFTED, N_COLOR_BEFORE),
    275: cx(TOP_RIGHT_CORNER_FULL_SHIFTED_SMALL, N_COLOR_BEFORE),
    250: cx(E_COLOR, TOP_RIGHT_CORNER_FULL_SHIFTED_SMALL, N_COLOR_BEFORE),
    179: E_COLOR,
    274: E_COLOR,
    298: E_COLOR,
    322: cx(E_COLOR, "rounded-bl-2xl"),
    323: E_COLOR,
    324: E_COLOR,
    325: E_COLOR,
    181: E_COLOR,
    182: cx(E_COLOR, "rounded-r-2xl"),
    254: cx(E_COLOR, "rounded-r-2xl"),
    253: E_COLOR,
    326: cx(E_COLOR, "rounded-r-2xl"),

    84: cx(Z_COLOR, "rounded-l-2xl"),
    85: Z_COLOR,
    86: Z_COLOR,
    87: Z_COLOR,
    88: cx(Z_COLOR, "rounded-tr-2xl"),
    111: cx(BOTTOM_RIGHT_CORNER_FULL, Z_COLOR_BEFORE),
    134: cx(BOTTOM_RIGHT_CORNER_FULL, Z_COLOR_BEFORE),
    157: cx(BOTTOM_RIGHT_CORNER_FULL, Z_COLOR_BEFORE),
    112: cx(TOP_LEFT_CORNER_FULL_SHIFTED, Z_COLOR_BEFORE),
    135: cx(TOP_LEFT_CORNER_FULL_SHIFTED, Z_COLOR_BEFORE),
    158: cx(TOP_LEFT_CORNER_FULL_SHIFTED, Z_COLOR_BEFORE),
    208: cx(Z_COLOR, "rounded-r-2xl"),
    207: Z_COLOR,
    206: Z_COLOR,
    205: Z_COLOR,

    256: cx(FRAME_COLOR, "rounded-tl-2xl"),
    280: FRAME_COLOR,
    304: FRAME_COLOR,
    328: FRAME_COLOR,
    352: FRAME_COLOR,
    376: cx(FRAME_COLOR, "rounded-br-2xl"),

    368: cx(FRAME_COLOR, "rounded-bl-2xl"),
    369: FRAME_COLOR,
    370: FRAME_COLOR,
    371: FRAME_COLOR,
    372: FRAME_COLOR,
    373: FRAME_COLOR,
    374: FRAME_COLOR,
    375: FRAME_COLOR,

    342: cx(FRAME_COLOR, "rounded-bl-2xl"),
    343: FRAME_COLOR,
    344: cx(FRAME_COLOR, "rounded-tr-2xl"),

    314: cx(FRAME_COLOR, "rounded-bl-2xl"),
    315: FRAME_COLOR,
    316: FRAME_COLOR,
    317: FRAME_COLOR,
    318: cx(FRAME_COLOR, "rounded-tr-2xl"),

    28: cx(FRAME_COLOR, "rounded-tl-2xl"),
    29: FRAME_COLOR,
    30: FRAME_COLOR,
    31: FRAME_COLOR,
    32: FRAME_COLOR,
    33: FRAME_COLOR,
    34: FRAME_COLOR,
    35: FRAME_COLOR,
    36: FRAME_COLOR,
    37: FRAME_COLOR,
    38: FRAME_COLOR,
    39: FRAME_COLOR,
    40: FRAME_COLOR,
    41: FRAME_COLOR,
    42: cx(FRAME_COLOR, "rounded-tr-2xl"),
    50: cx(FRAME_COLOR, "rounded-tl-2xl"),
    51: FRAME_COLOR,
    52: cx(FRAME_COLOR, "rounded-br-2xl"),
    66: FRAME_COLOR,
    90: FRAME_COLOR,
    114: FRAME_COLOR,
    138: FRAME_COLOR,
    162: FRAME_COLOR,
    186: FRAME_COLOR,
    210: FRAME_COLOR,
    234: FRAME_COLOR,
    258: cx(FRAME_COLOR, "rounded-br-2xl"),
    257: FRAME_COLOR,
    74: FRAME_COLOR,
    98: FRAME_COLOR,
    122: FRAME_COLOR,
    146: FRAME_COLOR,
    170: FRAME_COLOR,
    194: FRAME_COLOR,
    218: FRAME_COLOR,
    242: FRAME_COLOR,
    266: FRAME_COLOR,
    290: FRAME_COLOR,
}
